language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "GaVhrfxLj+jKJHGnYOv0WsyYrdT8ZgvdvoCcyRlDCHdANXukC0+g4Rd4aji6jyRYVk/Gsvl3iEvFx/objSvgkx30RX0tPWdO8qbq+3VsI5DKR+hT082nJDDtsacNNOV3JXTvZzRYTEYVb4jzQ6EPW0yS9PrimZIQV1G0lb7bKoYGCvL5hSU3SEg5GrQ3Cea3UeGUtYgMTS2BpUXs5Jpp1ugErSwT/bsGWA7X9SeFsISGo6Gm3+qhmN3BcmyZBrUH19GswBSHlnJgxaW/PTEWGt8BgjPwqqYTqzv/FF/5/cXzNLcj197h/u1FPPT6maaki/a63CtGSJr7WFzislghbBlZC1M0np0qpAGwVrWsTk27AjhQIOnJUvrzoTh+y6FfA1GbhN/W4mh8zU94DRaqOR1rAk6R+D1tUIMKw6HdafRJzxgERp3lvRCehiaInCLfPWm5Kcu1EhsuB5E0k0JAYZg1L7rnr5cxGu+TQCaWeto0cR7aXXjuAroR1NLx/smujUoXjLaYFUchrW8flhY/7PTuMnb5/SWtoMxZ77n2Yom8HLC84OPsp2YE1cTpi3xA/kx23wGRSimdFAHD47kCSrJweu5A2gDKSswuYo95PekZR84pNamSkyGF884JFl/yK9scie7d6K8ofuzkC2r+9khq3Zt2xGtJxrYJRpNi2rI="
    on:
      branch: master
