language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "AWMaHQUWyfL04LyyAqTeSDPphfl+ZOwHtar8LIYEae3Qz2o8dW0eyIdFu674Wo3ORF27/CojsSukv0RYtARuoI0qHs6ZRtFgtslHqB4Zvur8Jo24T6a8ncJrFatgp3uWSAIdSyvYjeIujo4A9SAa1Cyv4m1G0TcNvjR2iuHQFx0D5y8xSLLUQK4AlC7YiMNnnZjWekvdFMsMBg6asUBRx/JqZGPEnanlVUzYX71RE8HI+TN2lKydDTOFVqoJGThIRMz5vk6TOYxyrmoVwyVAtryTlav4K8h0TD2npFs32qR5tqNBUC0Ti7a47mj11aZCKSfoLgs0/ZJLiHV6hiqaNhqxOhR4pFBXx02MDJES8lxXxJNk9vvzCyXUSSZHh9+XFYSeilx7EmO5LApqPiDQpec/VvC6OBvUHddEQZ8pvMdJgxB92xo/CGdYiRqUrHJxFG8GmPEgubzOlk0lR5cEppsHuQ8d3vlgHDAQyClGPu/duvSjD7JvBXCBMTpfXZx6LoO8uUVwFxnR2fdge3JXvYAbtdU7ZxWWlNoT4OXeLBdNG5RulswFPhxz5lHb74Ctd9eRK/UX8S7kF9Quy1TfywfRr012gF9SQWdEHTcj74aKBcj1LvzgxzjgcGBa9r6X/wOABCmtLRCNATcSQb0QcghMeH/3jWvxV70rhMYWhmw="
    on:
      branch: master
