language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "Cd3K4IWSyhI3qfg/p706FZN996dP10R51/4cFchFhkYWNp84yxxJPBZaEIlzCTG42Gx+rIHv+BJkSaiYKnan3dLhMvrBcIS/VhYYTltllC5HVRaOiU7dp+qSkqFM/of9z7HASilVp7Sk/2WW0Lel1poFaPzku7VaieWz8ZW350SDTcdD6Y1JJhEFTPtWfUTFwJ908un8DO+DiAPmwVHHuD5aCT+aMBmFW2NEucjBqc23rtHfwhUI5qaGxotME2U4wkRgxPcwLgDWSyzIJFUl9UVBK/D0KG2m4SDoL8CmkU3PiknDgA2YcgTwJS/FGL/kXIBNX3djw32+EbgmxMMNmauOAnrunnT2VYQsbMGrqVCfqC9IhnYlboGlSpTAAwbgjUvy/e7OQCtK9Xj62DYow2noNo3JWWJiqUjZV8Rzwq4BDGMrvz0pGDcXT5Cu2flOPE/gUnruwphrtGrAYejzuaPj/hRf5BsmmvVjDv4uuLxe2CQxC4vTUaFnhxIpYEoCWsqVn2LFWBCRDGd6JmBIzA3CHwZDqfDWsCp6cl1q+NuBW2O2FXohBnfQsQYZiakkaLQQriQxDAxs3NVY68cx8H2Ak7TDc5B8Lv+enfiFoWok2/Yk6HKqjvmoKR0Bicz3hX3sInTUqU+pfZLnH9CZNNG3UoO95H7I0tl6xrBLEis="
  on:
    branch: master
